version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_service_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - product_service_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: product_service_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-product_service}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-product_service}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - product_service_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: product_service_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    networks:
      - product_service_network
    depends_on:
      - db

networks:
  product_service_network:
    driver: bridge

volumes:
  dbdata:
    driver: local 