# Debug settings
debug: false
trace: false

# Database credentials
database:
  driver: pgsql
  host: db
  port: 5432
  name: product_service
  user: product_service
  password: root

# Logging
log:
  level: info
  path: /var/www/logs
