# Debug settings
debug: true
trace: true

# Database credentials
database:
  driver: pgsql
  host: db
  port: 5432
  name: product_service
  user: product_service
  password: root

# Logging
log:
  level: debug
  path: /var/www/logs
